#!/bin/bash

# PCR (Pacman Cache Repository) Script (v1.37)
# https://github.com/yadieet/pcr
#
# yadieet sa <qts19bit@gmail.com>


if [[ $EUID == 0 ]]; then
   echo "Sorry but don't run this script root."
   exit
fi


if [[ -z $@ ]]; then
	echo "Cannot continue, missing arguments. (Use -h for help)"
	echo "Example : $ create-pcr -r \"core extra community multilib mate\" -o \"/data/\" -cp 0 -pi 1"
	exit
fi

for arg in "$@"
do
	if [[ $arg == "-h" ]]; then

echo "PCR (Pacman Cache Repository) Script (v1.37)"
echo "-- Create local repository from pacman cache."
echo "https://github.com/yadieet/pcr"
echo ""
echo "OPTIONS :"
echo "-r  : repositories, example : \"core extra community multilib mate\""
echo "-o  : output directory, must already exist. This script will create the 'PCR' directory under output directory."
echo "-cp : copy mode (default is '0'). If value is not '1', use linking mode."
echo "-pi : prefer installed (default is '1'). Use installed version of package if the current version and installed version of package are exists."
echo ""
echo "Example usage :"
echo "$ create-pcr -r \"core extra community multilib mate\" -o \"/data/\" -cp 0 -pi 1"
		exit
	fi
done

repoxs=0
iarg=1
for arg in "$@"
do
	((iarg++))
	if [[ $arg == "-r" ]]; then
		repoxs=${@:$iarg:1}
		break
	fi
done
if [[ $repoxs == 0 || -z $repoxs ]]; then
	echo "Cannot continue, please give some repoxs. (Example: -r \"core extra community multilib mate\")"
	exit
fi
if [[ ${repoxs:0:1} == '-' ]]; then
	echo "Invalid args for -r ."
	exit
fi

for repox in $repoxs
do
	pkglist=`pacman -Sl $repox`
	if [[ -z `echo "$pkglist" | awk {'print $1'}` ]]; then
		echo "Repox '$repox' not exist."
		exit
	fi
done

pacman_cache_dir="/var/cache/pacman/pkg/"
if [ ! -d "$pacman_cache_dir" ]; then
	echo "Cannot continue, pacman cache directory '$pacman_cache_dir' is not exist."
	exit
fi
if [ ! -r "$pacman_cache_dir" ]; then
	echo "Cannot continue, pacman cache directory '$pacman_cache_dir' is not readable."
	exit
fi

outdir=0
iarg=1
for arg in "$@"
do
	((iarg++))
	if [[ $arg == "-o" ]]; then
		outdir=${@:$iarg:1}
		break
	fi
done
if [[ "$outdir" == 0 || -z "$outdir" ]]; then
	echo "Cannot continue, please specify output directory. (Example: -o \"/data/\" )"
	exit
fi
if [ ! -d "$outdir" ]; then
	echo "Cannot continue, output directory '$outdir' is not exist."
	exit
fi
if [ ! -w "$outdir" ]; then
	echo "Cannot continue, output directory '$outdir' is not writable."
	exit
fi

copying=0
iarg=1
for arg in "$@"
do
	((iarg++))
	if [[ $arg == "-cp" ]]; then
		copying=${@:$iarg:1}
		break
	fi
done
if [[ "$copying" != 0 && $copying != 1 ]]; then
	copying=0
fi

prefer_installed=1
iarg=1
for arg in "$@"
do
	((iarg++))
	if [[ $arg == "-pi" ]]; then
		prefer_installed=${@:$iarg:1}
		break
	fi
done
if [[ "$prefer_installed" != 0 && $prefer_installed != 1 ]]; then
	prefer_installed=1
fi

echo "Configuration :"
echo "==============="
echo "Pacman cache directory         = '$pacman_cache_dir'"
echo "Repositories (-r)              = $repoxs"
echo "Output directory (-o)          = '$outdir'"
echo -n "Copy mode (-cp)                = ";  [[ $copying == 0 ]] && echo "no (linking)" || echo "yes"
echo -n "Prefer installed version (-pi) = ";  [[ $prefer_installed == 0 ]] && echo "no" || echo "yes"
echo ""

arch=`uname -m`

cd "$outdir"
if [ -e "PCR" ]; then
		echo "Cannot continue, 'PCR' directory in '$outdir' exist. Please remove 'PCR' directory first."
		exit
fi
mkdir -p "PCR/archlinux"
cd "PCR/archlinux"

t=0

function copyx() {
	((t++))
	echo "#"$t: Copying `ls $1` to [$2] directory.. [$3]
	cp -L $1 $2/os/$arch
}
function linkingx() {
	((t++))
	echo "#"$t: Linking `ls $1` to [$2] directory.. [$3]
	ln -s $1 $2/os/$arch
}

for repox in $repoxs
do
	mkdir -p $repox/os/$arch
		pkglist=`pacman -Sl $repox`
	while read pkg
	do
		pkgname=`echo $pkg | awk {'print $2'}`
		pkgver=`echo $pkg | awk {'print $3'}`
		filex=$pacman_cache_dir"$pkgname-$pkgver"*.pkg.tar.xz
		if [ ! -e $filex ]; then
			inspkg=$(echo "`pacman -Q`" | grep -m 1 "^$pkgname")
			if [[ ! -z "$inspkg" ]]; then
				insver=`echo "$inspkg" | awk {'print $2'}`
				if [[ "$pkgver" != "$insver" ]];then
					filexx=$pacman_cache_dir"$pkgname-$insver"*.pkg.tar.xz
					if [ -e $filexx ]; then
						[[ $copying == 1 ]] && copyx $filexx $repox 3 || linkingx $filexx $repox 3
					else
						echo - $pkgname-$pkgver package file is not exist. [2]
					fi
				else
					echo - $pkgname-$pkgver package file is not exist. [1]
				fi
			else
				echo - $pkgname-$pkgver package file is not exist. [0]
			fi
		else
			if [[ $prefer_installed == 1 ]]; then
				inspkg=$(echo "`pacman -Q`" | grep -m 1 "^$pkgname")
				if [[ ! -z "$inspkg" ]]; then
					insver=`echo "$inspkg" | awk {'print $2'}`
					if [[ "$pkgver" != "$insver" ]];then
						filexx=$pacman_cache_dir"$pkgname-$insver"*.pkg.tar.xz
						if [ ! -e $filexx ]; then
							[[ $copying == 1 ]] && copyx $filex $repox 8 || linkingx $filex $repox 8
						else
							[[ $copying == 1 ]] && copyx $filexx $repox 7 || linkingx $filexx $repox 7
						fi
					else
						[[ $copying == 1 ]] && copyx $filex $repox 6 || linkingx $filex $repox 6
					fi
				else
					[[ $copying == 1 ]] && copyx $filex $repox 5 || linkingx $filex $repox 5
				fi
			else	
				[[ $copying == 1 ]] && copyx $filex $repox 4 || linkingx $filex $repox 4
			fi
		fi
		done < <(echo "$pkglist")
done

for repox in $repoxs
do
	cd "$outdir/PCR/archlinux/$repox/os/$arch"
	repo-add $repox.db.tar.gz *.pkg.tar.xz
done

echo "======================================="
echo "Total: $t packages."
